# Site information
domainname: "eduteams.local"
idp_hostname: "idp.{{ domainname }}"
sp_hostname: "sp.{{ domainname }}"
op_hostname: "https://op.{{ domainname }}"

cert_hostname: "*.{{ domainname }}"

letsencrypt_email: idp@eduteams.local
letsencrypt_domain: "{{ domainname }}"
letsencrypt_request_www: false
 apache is installed first and claims port 80. Pause it to allow LetsEncrypt to request a certificate
letsencrypt_pause_services: [apache2]

ssp_version: 1.15.4
ssp_hostname: "{{ idp_hostname }}"
ssp_subject: "{{ cert_subject }}"
ssp_days_valid: "{{ cert_days_valid }}"
ssp_key: "{{ domainname }}.pem"
ssp_certificate: "{{ domainname }}.crt"
ssp_auth_admin_password: "edu2play"
ssp_technicalcontact_name: Contact
ssp_technicalcontact_email: postmaster@{{ idp_hostname }}
ssp_managingcontact_name: Manager
ssp_managingcontact_email: webmaster@{{ idp_hostname }}
#spp_sp_metadata: "{{ sp_hostname }}/authentication/sp/metadata"
#spp_sp_consumer: "{{ sp_hostname }}/authentication/sp/consume-assertion"
ssp_title_suffix: INACADEMIA.LOCAL

ssl_idp_hostname: "{{ idp_hostname }}"
ssl_sp_hostname: "{{ sp_hostname }}"
ssl_webmaster: "webmaster@{{ domainname }}"
ssl_docroot: "{{ ssp_dir }}/www"
